"""initial schema

Revision ID: c1fcfd7fe014
Revises: 
Create Date: 2026-08-10 21:09:50.140157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1fcfd7fe014'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_score_options',
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('armor_proficiency_options',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('feature_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effect_type', sa.String(length=30), nullable=False),
    sa.Column('effect_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_grants_source_id'), 'feature_grants', ['source_id'], unique=False)
    op.create_index(op.f('ix_feature_grants_source_type'), 'feature_grants', ['source_type'], unique=False)
    op.create_table('tool_proficiency_options',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weapon_proficiency_options',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('background_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_invite_code'), 'campaigns', ['invite_code'], unique=True)
    op.create_table('class_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('skill_choices', sa.Integer(), nullable=False),
    sa.Column('subclass_level', sa.Integer(), nullable=False),
    sa.Column('spell_ability', sa.String(length=3), nullable=True, foreign_key='ability_score_options.name'),
    sa.Column('spellcasting_type', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ability_score', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['ability_score'], ['ability_score_options.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ability_score')
    )
    op.create_table('feat_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('level_prerequisite', sa.Integer(), nullable=False),
    sa.Column('prerequisite_description', sa.Text(), nullable=True),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=30), nullable=True),
    sa.Column('rarity', sa.String(length=15), nullable=False),
    sa.Column('requires_attunement', sa.Boolean(), nullable=False),
    sa.Column('attunement_prerequisite', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cost_gp', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('species_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creature_type', sa.String(length=30), nullable=False),
    sa.Column('size', sa.Enum('tiny', 'small', 'medium', 'large', 'huge', 'gargantuan', name='creaturesize'), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('special_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spell_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=20), nullable=False),
    sa.Column('casting_time', sa.String(length=50), nullable=False),
    sa.Column('range', sa.String(length=50), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material_component', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('higher_levels', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_armor_proficiencies',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('armor_proficiency', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['armor_proficiency'], ['armor_proficiency_options.name'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'armor_proficiency')
    )
    op.create_table('class_primary_abilities',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('ability_score', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['ability_score'], ['ability_score_options.name'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'ability_score')
    )
    op.create_table('class_saving_throws',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('ability_score', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['ability_score'], ['ability_score_options.name'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'ability_score')
    )
    op.create_table('class_tool_proficiencies',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('tool_proficiency', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_proficiency'], ['tool_proficiency_options.name'], ),
    sa.PrimaryKeyConstraint('class_id', 'tool_proficiency')
    )
    op.create_table('class_weapon_proficiencies',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('weapon_proficiency', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_proficiency'], ['weapon_proficiency_options.name'], ),
    sa.PrimaryKeyConstraint('class_id', 'weapon_proficiency')
    )
    op.create_table('class_skills',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'skill_id')
    )
    op.create_table('class_initial_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('option', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_class_initial_equipment_quantity_positive'),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell_class_lists',
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spell_id', 'class_id')
    )
    op.create_table('subclass_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_homebrew', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('experience_points', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=True),
    sa.Column('background_id', sa.UUID(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('temp_hp', sa.Integer(), nullable=False),
    sa.Column('death_saves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exhaustion_level', sa.Integer(), nullable=False),
    sa.Column('inspiration', sa.Boolean(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spell_slots_remaining', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['background_id'], ['background_definitions.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('subclass_id', sa.UUID(), nullable=True),
    sa.Column('hit_dice_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['class_definitions.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclass_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'class_id')
    )
    op.create_table('character_ability_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('ability_score', sa.String(length=3), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value >= 1 AND value <= 30', name='ck_character_ability_scores_value_bounds'),
    sa.ForeignKeyConstraint(['ability_score'], ['ability_score_options.name'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'ability_score')
    )
    op.create_table('character_feats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('feat_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feat_id'], ['feat_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('attuned', sa.Boolean(), nullable=False),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('resource_name', sa.String(length=50), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('remaining_uses', sa.Integer(), nullable=False),
    sa.Column('reset_on', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_spell_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('spell_level', sa.Integer(), nullable=False),
    sa.Column('remaining_slots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_spells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('spell_id', sa.UUID(), nullable=False),
    sa.Column('is_prepared', sa.Boolean(), nullable=False),
    sa.Column('is_always_prepared', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spell_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_spells')
    op.drop_table('character_spell_slots')
    op.drop_table('character_resources')
    op.drop_table('character_inventory')
    op.drop_table('character_feats')
    op.drop_table('character_ability_scores')
    op.drop_table('character_classes')
    op.drop_table('characters')
    op.drop_table('subclass_definitions')
    op.drop_table('spell_class_lists')
    op.drop_table('class_initial_equipment')
    op.drop_table('class_skills')
    op.drop_table('class_weapon_proficiencies')
    op.drop_table('class_tool_proficiencies')
    op.drop_table('class_saving_throws')
    op.drop_table('class_primary_abilities')
    op.drop_table('class_armor_proficiencies')
    op.drop_table('campaign_members')
    op.drop_table('spell_definitions')
    op.drop_table('species_definitions')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('item_definitions')
    op.drop_table('feat_definitions')
    op.drop_table('skill_definitions')
    op.drop_table('class_definitions')
    op.drop_index(op.f('ix_campaigns_invite_code'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('background_definitions')
    op.drop_table('weapon_proficiency_options')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tool_proficiency_options')
    op.drop_index(op.f('ix_feature_grants_source_type'), table_name='feature_grants')
    op.drop_index(op.f('ix_feature_grants_source_id'), table_name='feature_grants')
    op.drop_table('feature_grants')
    op.drop_table('armor_proficiency_options')
    op.drop_table('ability_score_options')
    # ### end Alembic commands ###
    # `op.drop_table` does not remove the shared Postgres ENUM type used by
    # `species_definitions.size`; drop it explicitly so downgrade is a true
    # inverse of upgrade (required for a clean downgrade/upgrade round-trip).
    sa.Enum(name='creaturesize').drop(op.get_bind(), checkfirst=True)
