"""SRD 2024 feats, gerado por scripts/extract_srd_feats.py — não editar à mão.

Só dados (sem import de `app`): importado pela migration c1fcfd7fe014. Para mudar,
ajuste o extrator e rode `python -m scripts.extract_srd_feats` em backend/.
Estrutura das features: mesmos nomes do payload da API (efeitos esparsos; a
migration completa os defaults).
"""

FEATS = ({'name': 'Alert',
  'category_code': 'origin',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': (),
  'features': ({'name': 'Initiative Proficiency',
                'description': 'When you roll Initiative, you can add your Proficiency Bonus to the roll.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'bonus',
                             'target_code': 'initiative',
                             'value_basis_code': 'proficiency_bonus'},),
                'resources': ()},
               {'name': 'Initiative Swap',
                'description': 'Immediately after you roll Initiative, you can swap your Initiative with the '
                               "Initiative of one willing ally in the same combat. You can't make this swap if you or "
                               'the ally has the Incapacitated condition.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Magic Initiate',
  'category_code': 'origin',
  'description': 'You gain the following benefits.\n'
                 '\n'
                 'You can take this feat more than once, but you must choose a different spell list each time.',
  'repeatable': True,
  'prerequisites': (),
  'features': ({'name': 'Two Cantrips',
                'description': 'You learn two cantrips of your choice from the Cleric, Druid, or Wizard spell list. '
                               "Intelligence, Wisdom, or Charisma is your spellcasting ability for this feat's spells "
                               '(choose when you select this feat).',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},
               {'name': 'Level 1 Spell',
                'description': "Choose a level 1 spell from the same list you selected for this feat's cantrips. You "
                               'always have that spell prepared. You can cast it once without a spell slot, and you '
                               'regain the ability to cast it in that way when you finish a Long Rest. You can also '
                               'cast the spell using any spell slots you have.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},
               {'name': 'Spell Change',
                'description': 'Whenever you gain a new level, you can replace one of the spells you chose for this '
                               'feat with a different spell of the same level from the chosen spell list.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Savage Attacker',
  'category_code': 'origin',
  'description': "You've trained to deal particularly damaging strikes. Once per turn when you hit a target with a "
                 "weapon, you can roll the weapon's damage dice twice and use either roll against the target.",
  'repeatable': False,
  'prerequisites': (),
  'features': ({'name': 'Savage Attacker',
                'description': "You've trained to deal particularly damaging strikes. Once per turn when you hit a "
                               "target with a weapon, you can roll the weapon's damage dice twice and use either roll "
                               'against the target.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},)},
 {'name': 'Skilled',
  'category_code': 'origin',
  'description': 'You gain proficiency in any combination of three skills or tools of your choice.\n'
                 '\n'
                 'You can take this feat more than once.',
  'repeatable': True,
  'prerequisites': (),
  'features': ({'name': 'Skilled',
                'description': 'You gain proficiency in any combination of three skills or tools of your choice.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'grant',
                             'choice': {'pool_type_code': 'skill_or_tool', 'choose_count': 3}},),
                'resources': ()},)},
 {'name': 'Ability Score Improvement',
  'category_code': 'general',
  'description': 'Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. '
                 "This feat can't increase an ability score above 20.\n"
                 '\n'
                 'You can take this feat more than once.',
  'repeatable': True,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 4,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Improvement',
                'description': 'Increase one ability score of your choice by 2, or increase two ability scores of your '
                               "choice by 1. This feat can't increase an ability score above 20.",
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 20,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 2, 'allow_repeat': True}},),
                'resources': ()},)},
 {'name': 'Grappler',
  'category_code': 'general',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 4,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},
                    {'or_group': 2,
                     'min_character_level': None,
                     'ability_code': 'str',
                     'min_score': 13,
                     'feature_kind_code': None},
                    {'or_group': 2,
                     'min_character_level': None,
                     'ability_code': 'dex',
                     'min_score': 13,
                     'feature_kind_code': None}),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase your Strength or Dexterity score by 1, to a maximum of 20.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 20,
                             'choice': {'pool_type_code': 'ability_score',
                                        'choose_count': 1,
                                        'options': ({'ability_code': 'str'}, {'ability_code': 'dex'})}},),
                'resources': ()},
               {'name': 'Punch and Grab',
                'description': 'When you hit a creature with an Unarmed Strike as part of the Attack action on your '
                               'turn, you can use both the Damage and the Grapple option. You can use this benefit '
                               'only once per turn.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},
               {'name': 'Attack Advantage',
                'description': 'You have Advantage on attack rolls against a creature Grappled by you.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'advantage',
                             'target_code': 'attack_roll',
                             'condition_text': 'against a creature Grappled by you'},),
                'resources': ()},
               {'name': 'Fast Wrestler',
                'description': "You don't have to spend extra movement to move a creature Grappled by you if the "
                               'creature is your size or smaller.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Archery',
  'category_code': 'fighting_style',
  'description': 'You gain a +2 bonus to attack rolls you make with Ranged weapons.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': None,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': 'fighting_style'},),
  'features': ({'name': 'Archery',
                'description': 'You gain a +2 bonus to attack rolls you make with Ranged weapons.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'bonus',
                             'target_code': 'attack_roll',
                             'value': 2,
                             'condition_text': 'with Ranged weapons'},),
                'resources': ()},)},
 {'name': 'Defense',
  'category_code': 'fighting_style',
  'description': "While you're wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor Class.",
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': None,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': 'fighting_style'},),
  'features': ({'name': 'Defense',
                'description': "While you're wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor "
                               'Class.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'bonus',
                             'target_code': 'armor_class',
                             'value': 1,
                             'condition_text': 'while wearing Light, Medium, or Heavy armor'},),
                'resources': ()},)},
 {'name': 'Great Weapon Fighting',
  'category_code': 'fighting_style',
  'description': 'When you roll damage for an attack you make with a Melee weapon that you are holding with two hands, '
                 'you can treat any 1 or 2 on a damage die as a 3. The weapon must have the Two-Handed or Versatile '
                 'property to gain this benefit.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': None,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': 'fighting_style'},),
  'features': ({'name': 'Great Weapon Fighting',
                'description': 'When you roll damage for an attack you make with a Melee weapon that you are holding '
                               'with two hands, you can treat any 1 or 2 on a damage die as a 3. The weapon must have '
                               'the Two-Handed or Versatile property to gain this benefit.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},)},
 {'name': 'Two-Weapon Fighting',
  'category_code': 'fighting_style',
  'description': 'When you make an extra attack as a result of using a weapon that has the Light property, you can add '
                 "your ability modifier to the damage of that attack if you aren't already adding it to the damage.",
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': None,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': 'fighting_style'},),
  'features': ({'name': 'Two-Weapon Fighting',
                'description': 'When you make an extra attack as a result of using a weapon that has the Light '
                               "property, you can add your ability modifier to the damage of that attack if you aren't "
                               'already adding it to the damage.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},)},
 {'name': 'Boon of Combat Prowess',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase one ability score of your choice by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 1}},),
                'resources': ()},
               {'name': 'Peerless Aim',
                'description': 'When you miss with an attack roll, you can hit instead. Once you use this benefit, you '
                               "can't use it again until the start of your next turn.",
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Boon of Dimensional Travel',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase one ability score of your choice by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 1}},),
                'resources': ()},
               {'name': 'Blink Steps',
                'description': 'Immediately after you take the Attack action or the Magic action, you can teleport up '
                               'to 30 feet to an unoccupied space you can see.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Boon of Fate',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase one ability score of your choice by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 1}},),
                'resources': ()},
               {'name': 'Improve Fate',
                'description': 'When you or another creature within 60 feet of you succeeds on or fails a D20 Test, '
                               'you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. '
                               "Once you use this benefit, you can't use it again until you roll Initiative or finish "
                               'a Short or Long Rest.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ({'name': 'Improve Fate',
                               'value': 1,
                               'recharges': ({'recharge_type_code': 'initiative', 'recovers': None},
                                             {'recharge_type_code': 'short_rest', 'recovers': None},
                                             {'recharge_type_code': 'long_rest', 'recovers': None})},)})},
 {'name': 'Boon of Irresistible Offense',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase your Strength or Dexterity score by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score',
                                        'choose_count': 1,
                                        'options': ({'ability_code': 'str'}, {'ability_code': 'dex'})}},),
                'resources': ()},
               {'name': 'Overcome Defenses',
                'description': 'The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},
               {'name': 'Overwhelming Strike',
                'description': 'When you roll a 20 on the d20 for an attack roll, you can deal extra damage to the '
                               "target equal to the ability score increased by this feat. The extra damage's type is "
                               "the same as the attack's type.",
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Boon of Spell Recall',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},
                    {'or_group': 2,
                     'min_character_level': None,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': 'spellcasting'}),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score',
                                        'choose_count': 1,
                                        'options': ({'ability_code': 'int'},
                                                    {'ability_code': 'wis'},
                                                    {'ability_code': 'cha'})}},),
                'resources': ()},
               {'name': 'Free Casting',
                'description': 'Whenever you cast a spell with a level 1–4 spell slot, roll 1d4. If the number you '
                               "roll is the same as the slot's level, the slot isn't expended.",
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()})},
 {'name': 'Boon of the Night Spirit',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase one ability score of your choice by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 1}},),
                'resources': ()},
               {'name': 'Merge with Shadows',
                'description': 'While within Dim Light or Darkness, you can give yourself the Invisible condition as a '
                               'Bonus Action. The condition ends on you immediately after you take an action, a Bonus '
                               'Action, or a Reaction.',
                'level': None,
                'action_type_code': 'bonus_action',
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': (),
                'resources': ()},
               {'name': 'Shadowy Form',
                'description': 'While within Dim Light or Darkness, you have Resistance to all damage except Psychic '
                               'and Radiant.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'damage_resistance',
                             'damage_type_code': 'acid',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'bludgeoning',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'cold',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'fire',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'force',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'lightning',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'necrotic',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'piercing',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'poison',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'slashing',
                             'condition_text': 'while within Dim Light or Darkness'},
                            {'operation_code': 'damage_resistance',
                             'damage_type_code': 'thunder',
                             'condition_text': 'while within Dim Light or Darkness'}),
                'resources': ()})},
 {'name': 'Boon of Truesight',
  'category_code': 'epic_boon',
  'description': 'You gain the following benefits.',
  'repeatable': False,
  'prerequisites': ({'or_group': 1,
                     'min_character_level': 19,
                     'ability_code': None,
                     'min_score': None,
                     'feature_kind_code': None},),
  'features': ({'name': 'Ability Score Increase',
                'description': 'Increase one ability score of your choice by 1, to a maximum of 30.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'ability_score_increase',
                             'value': 1,
                             'max_value': 30,
                             'choice': {'pool_type_code': 'ability_score', 'choose_count': 1}},),
                'resources': ()},
               {'name': 'Truesight',
                'description': 'You have Truesight with a range of 60 feet.',
                'level': None,
                'action_type_code': None,
                'feature_kind_code': None,
                'is_choice_option': False,
                'replaces': None,
                'effects': ({'operation_code': 'grant', 'sense_code': 'truesight', 'value': 60},),
                'resources': ()})})
